#pragma once

// HierarchicalID — see ARCHITECTURE.md §3.1
//
// {SwarmID(16-bit), UnitID(UUID v4, 128-bit)} = swarm-scoped, hardware-independent
// identity for a robot. SwarmID is assigned at deployment time; UnitID is the
// self-sovereign UUID generated by UUID::generate() in unsigned mode (v0.1) or,
// in signed mode, derived from a public key (§3.3, v0.2).
//
// String form: "SSSS:xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx"  (41 chars)
//   SSSS  — SwarmID, lowercase hex, zero-padded to 4 chars
//   xxx   — UUID canonical form per RFC 4122
//
// No exceptions. Malformed input to from_string() returns std::nullopt.
//
// Lexicographic ordering is (swarm_id, unit_id) — matching the string form.
//
// The BROADCAST sentinel referenced by §7.3 Message::recipient is intentionally
// NOT defined here. It is a §7 Messaging-layer concept and lands with the comms
// work in v0.2 — keeping it out of §3 prevents the identity layer from owning
// addressing semantics it shouldn't.

#include "mith/api_stability.h"
#include "mith/identity/uuid.h"

#include <cstddef>
#include <cstdint>
#include <functional>
#include <optional>
#include <string>
#include <string_view>

namespace mith {

using SwarmID = std::uint16_t;

struct MITH_STABLE_API HierarchicalID {
    SwarmID swarm_id = 0;
    UUID    unit_id;

    // Construct a fresh HierarchicalID with a random RFC 4122 v4 unit_id. Thread-safe.
    static HierarchicalID generate(SwarmID swarm) noexcept;

    // Parse the canonical 41-char form. Case-insensitive in hex digits.
    // Returns nullopt on any deviation (length, separator, hex, UUID structure).
    static std::optional<HierarchicalID> from_string(std::string_view s) noexcept;

    // Canonical lowercase 41-char form.
    std::string to_string() const;

    friend constexpr bool operator==(const HierarchicalID& a, const HierarchicalID& b) noexcept {
        return a.swarm_id == b.swarm_id && a.unit_id == b.unit_id;
    }
    friend constexpr bool operator!=(const HierarchicalID& a, const HierarchicalID& b) noexcept {
        return !(a == b);
    }
    friend constexpr bool operator<(const HierarchicalID& a, const HierarchicalID& b) noexcept {
        if (a.swarm_id != b.swarm_id) return a.swarm_id < b.swarm_id;
        return a.unit_id < b.unit_id;
    }
    friend constexpr bool operator>(const HierarchicalID& a, const HierarchicalID& b) noexcept {
        return b < a;
    }
    friend constexpr bool operator<=(const HierarchicalID& a, const HierarchicalID& b) noexcept {
        return !(b < a);
    }
    friend constexpr bool operator>=(const HierarchicalID& a, const HierarchicalID& b) noexcept {
        return !(a < b);
    }
};

} // namespace mith

namespace std {

template<>
struct hash<mith::HierarchicalID> {
    std::size_t operator()(const mith::HierarchicalID& h) const noexcept;
};

} // namespace std
